name: .NET

on:
    push:
        branches:
            - master
            - develop
            - test-branch
            - change-project-structure
    pull_request:
        branches:
            - master
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.0.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Upload photo to debug directory
              run: |
                cp tests/CoinyProject.Application.AlbumService.Tests/Shared/test.jpg tests/CoinyProject.Application.AlbumService.Tests/bin/Debug/net8.0/
                mkdir -p tests/CoinyProject.Application.AlbumService.Tests/test/albums/elements

            - name: Test
              run: dotnet test --no-build --verbosity normal